name: CMD-microwgs
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::ariba=2.14.4
    - bioconda::mlst=2.18.1
    - bioconda::chewbbaca=2.1.0
    - bioconda::kraken=1.1.1
    - bioconda::bracken=1.0.0
    - bioconda::spades=3.14.0
    - bioconda::quast=5.0.2
    - bioconda::freebayes=1.3.2
    - bioconda::bwa=0.7.17
    - bioconda::samtools=1.9
    - bioconda::picard=2.18.26
    - bioconda::sambamba=0.7.1
    - bioconda::bedtools=2.29.2
    - bioconda::perl-app-cpanminus==1.7044